import 'package:flutter/material.dart';
import './decryption.dart';
import './encryption.dart';

class Alg extends StatelessWidget {
  ScrollController s = ScrollController();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          centerTitle: true,
          backgroundColor: Colors.grey[900],
          title: const SelectableText('THE ALGORITHM',
              style: TextStyle(fontSize: 17.0, fontWeight: FontWeight.bold)),
        ),
        backgroundColor: _getColorFromHex("#971208"),
        body: Column(children: [
          const Padding(
              padding: EdgeInsets.only(top: 15),
              child: SelectableText(
                  "REVERSE-SWAP-INDEX-SHIFTING\n(RSIS ALGORITHM)\n",
                  textAlign: TextAlign.center,
                  style: TextStyle(
                      fontFamily: "Mono",
                      fontSize: 20.0,
                      fontWeight: FontWeight.bold,
                      color: Colors.black))),
          SizedBox(
            height: MediaQuery.of(context).size.height * 0.7,
            child: RawScrollbar(
                thumbColor: const Color.fromARGB(255, 0, 0, 0),
                radius: const Radius.circular(20),
                thumbVisibility: true,
                controller: s,
                thickness: 15,
                child: ListView(
                    padding: const EdgeInsets.only(
                        left: 15.0, right: 15.0, bottom: 15.0),
                    children: <Widget>[
                      Container(
                        color: Colors.black,
                        height: 2,
                        width: 1000,
                      ),
                      Container(
                          padding: const EdgeInsets.all(5),
                          height: 150,
                          child: Row(
                            children: [
                              const Icon(
                                Icons.lock_outline,
                                size: 100,
                                color: Colors.black,
                              ),
                              Container(width: 30),
                              const SelectableText("ENCRYPT\nMESSAGES",
                                  style: TextStyle(
                                      fontFamily: "Alfa",
                                      fontSize: 28.0,
                                      color: Colors.black))
                            ],
                          )),
                      Container(
                        color: Colors.black,
                        height: 2,
                        width: 1000,
                      ),
                      Container(height: 20),
                      const SelectableText(
                          "The initial string is split into 2 and swapped with each other.If the string length is odd,the character in the middle will remain in the same position.Now do the pervious step for each of the swapped halves.We have 4 quarters of swapped strings merged into a single string.Reverse the 1st and 3rd quarter.For each character of the string find it's ASCII code , say 'x'.Calculating the new value, say y, for every index value, i, using the formula given below:\n\ny(i)={[x + (i+1)*(sum of the digits of x)]%94}+32\n\nReplace x with y in the string.Encrypted String is Obtained!KEY is Generated by taking all the (sum of the digits of x values) and appending them to a string with a - between each values.\n",
                          style: TextStyle(
                              fontSize: 14.0,
                              fontFamily: 'OpB',
                              fontWeight: FontWeight.bold,
                              color: Colors.black)),
                      const SelectableText("EXAMPLE",
                          style: TextStyle(
                              fontSize: 16.0,
                              fontFamily: 'Mono',
                              fontWeight: FontWeight.bold,
                              color: Colors.black)),
                      Container(
                        height: 10,
                      ),
                      const SelectableText(
                          "ORIGINAL MESSAGE: \"ABCDEFGHIJ\"\nStep 1 : A B C D E F G H I J\nStep 2 : F G H I J A B C D E\nStep 3 : I J H F G D E C A B\nStep 4 : J I H F G E D C A B\nStep 5 : 74 73 72 70 71 69 68 67 65 66 (ASCII)\nStep 6 : INDEX SHIFTING",
                          style: TextStyle(
                              fontSize: 15.0,
                              fontFamily: 'Mono',
                              //fontWeight: FontWeight.bold,
                              color: Colors.black)),
                      const Padding(
                          padding:
                              EdgeInsets.only(left: 50, top: 10, bottom: 10),
                          child: SelectableText(
                              "Y(0)={[74+(1*11)]%94}+32=117\nY(1)={[73+(2*10)]%94}+32=125\nY(2)={[72+(3*9)]%94}+32=37\nY(3)={[70+(4*7)]%94}+32=36\nY(4)={[71+(5*8)]%94}+32=49\nY(5)={[69+(6*15)]%94}+32=97\nY(6)={[68+(7*14)]%94}+32=104\nY(7)={[67+(8*13)]%94}+32=109\nY(8)={[65+(9*11)]%94}+32=102\nY(9)={[66+(10*12)]%94}+32=124",
                              style: TextStyle(
                                  fontSize: 16.0,
                                  fontFamily: 'Mono',
                                  //fontWeight: FontWeight.bold,
                                  color: Colors.black))),
                      const SelectableText(
                          "Step 7 : 117 125 37 36 49 97 104 109 102 124\nYOUR ENCRYPTED STRING: \"u}%\$1ahmf|\"\nKEY:11-10-9-7-8-15-14-13-11-12\n",
                          style: TextStyle(
                              fontSize: 15.0,
                              fontFamily: 'Mono',
                              //fontWeight: FontWeight.bold,
                              color: Colors.black)),
                      Container(
                        color: Colors.black,
                        height: 2,
                        width: 1000,
                      ),
                      Container(
                          padding: const EdgeInsets.all(5),
                          height: 150,
                          child: Row(
                            children: [
                              const Icon(
                                Icons.lock_open,
                                size: 100,
                                color: Colors.black,
                              ),
                              Container(width: 30),
                              const SelectableText("DECRYPT\nMESSAGES",
                                  style: TextStyle(
                                      fontFamily: "Alfa",
                                      fontSize: 28.0,
                                      color: Colors.black))
                            ],
                          )),
                      Container(
                        color: Colors.black,
                        height: 2,
                        width: 1000,
                      ),
                      Container(height: 20),
                      const SelectableText(
                          "Find the ASCII values of all the characters of the string given.Let K be the Key code of length as same as the cyptic message.For each character, x, calculate the new value, y, for all index, i,using:\n\ny(i)={(x-32)-[(i+1)*k(i)]}%94\n\nIf the mod value is below 32,add 94!\n\nNow divide it into 4 quarters.Reverse the 1st and 3rd quarter.If length is odd , the middle element remains unchanged.Swap 1st and 2nd quarter.Swap 3rd and 4th quarter.Divide the string into 2 swap both the halves.If length is odd,the middle element is left untouched.Your Original message is extracted and found!!!\n",
                          style: TextStyle(
                              fontSize: 14.0,
                              fontFamily: 'OpB',
                              fontWeight: FontWeight.bold,
                              color: Colors.black)),
                      const SelectableText("EXAMPLE",
                          style: TextStyle(
                              fontSize: 16.0,
                              fontFamily: 'Mono',
                              fontWeight: FontWeight.bold,
                              color: Colors.black)),
                      Container(
                        height: 10,
                      ),
                      const SelectableText(
                          "CRYPTIC MESSAGE: \"u}%\$1ahmf|\"\nKEY:11-10-9-7-8-15-14-13-11-12\nStep 1 : 117 125 37 36 49 97 104 109 102 124\nStep 2 : INDEX SHIFTING",
                          style: TextStyle(
                              fontSize: 15.0,
                              fontFamily: 'Mono',
                              //fontWeight: FontWeight.bold,
                              color: Colors.black)),
                      const Padding(
                          padding:
                              EdgeInsets.only(left: 50, top: 10, bottom: 10),
                          child: SelectableText(
                              "Y(0)={(117-32)-(1*11)}%94=74\nY(1)={(125-32)-(2*10)}%94=73\nY(2)={(37-32)-(3*9)}%94=72\nY(3)={(36-32)-(4*7)}%94=70\nY(4)={(49-32)-(5*8)}%94=71\nY(5)={(97-32)-(6*15)}%94=69\nY(6)={(104-32)-(7*14)}%94=68\nY(7)={(109-32)-(8*13)}%94=67\nY(8)={(102-32)-(9*11)}%94=65\nY(9)={(124-32)-(10*12)}%94=66",
                              style: TextStyle(
                                  fontSize: 16.0,
                                  fontFamily: 'Mono',
                                  //fontWeight: FontWeight.bold,
                                  color: Colors.black))),
                      const SelectableText(
                          "Step 3 : 74 73 72 70 71 69 68 67 65 66 (ASCII)\nStep 4 : J I H F G E D C A B\nStep 5 : I J H F G D E C A B\nStep 6 : F G H I J A B C D E\nStep 7 : A B C D E F G H I J\nORIGINAL MESSAGE: \"ABCDEFGHIJ\"\n",
                          style: TextStyle(
                              fontSize: 15.0,
                              fontFamily: 'Mono',
                              //fontWeight: FontWeight.bold,
                              color: Colors.black)),
                      const Center(
                        child: Icon(
                          Icons.lock,
                          size: 150,
                          color: Colors.black,
                        ),
                      )
                    ])),
          ),
        ]));
  }
}

_getColorFromHex(String hexColor) {
  hexColor = hexColor.replaceAll("#", "");
  if (hexColor.length == 6) {
    hexColor = "FF$hexColor";

    return Color(int.parse("0x$hexColor"));
  }

  if (hexColor.length == 8) {
    return Color(int.parse("0x$hexColor"));
  }
}
